### ISSUE TITLE
当连接 redis 时指定参数 decode_responses=True 时，读取时 100%报错

### ISSUE THREAD

**Issue by Monster0303** [tair-opensource/tair-py#59]
必现的关键参数就是这个 decode_responses = True 时

```python
    def connect(self, db):
        r = Tair.from_url(host=host, db=db, password=passwd, decode_responses=True)
```

必现bug，当连接 redis 时指定参数 decode_responses=True 时，如果使用 exhash 或 exzset 类型，读取时 100%报错
![image](https://github.com/tair-opensource/tair-py/assets/40815364/ccfc6176-a509-4904-b1e0-958cf23e95ea)

exhash 类型也有一样的 bug，只要指定了 decode_responses=True，必现
![image](https://github.com/tair-opensource/tair-py/assets/40815364/39724d5b-06d4-4f23-8cbb-71f44b017ea1)

经过提工单（000B99A97C）核实，确实需要优化，让我来这边反馈下
![image](https://github.com/tair-opensource/tair-py/assets/40815364/0d1a3bba-63d4-4e0c-bb21-1f1fca070e4f)
![image](https://github.com/tair-opensource/tair-py/assets/40815364/04d95c88-0bcb-4d3e-a19b-c3fa742dbc65)

希望 tair-py 也可以做下兼容，谢谢

**Comment by Monster0303** [comment]
目前我只用到了 exzset 和 exhash，但猜测这种错误会出现在所有 tair 特有的数据类型中

**Comment by yangbodong22011** [comment]
@Monster0303 感谢反馈，此优化正在进行中。在此之前，请您使用 decode_responses 的默认参数：False。

**Comment by yangbodong22011** [comment]
@Monster0303 PR 合并了，并发布了 [1.3.7](https://github.com/tair-opensource/tair-py/releases/tag/v1.3.7) 版本。可以试试。
