### ISSUE TITLE
TVS functions got ResponseError: unknown command `TVS.CREATEINDEX`, with args beginning with: ....

### ISSUE THREAD

**Issue by rifandyzv** [tair-opensource/tair-py#62]
I try to execute TVS function like these
![image](https://github.com/tair-opensource/tair-py/assets/61496024/2a4a7a2b-76d3-457d-a4b8-e6c4aab24927)

but they got unkown command, do you execute this right? or do you have any clear documentation regarding how to use the TVS functions on python?

**Comment by yangbodong22011** [comment]
@rifandyzv Hi, maybe you need to check whether your tair version is version 6.0, which only supports TairVector. https://www.aliyun.com/product/apsaradb/kvstore/tair

**Comment by rifandyzv** [comment]
Now already using Tair with Redis 6.0 Cluster edition, but this is what I got. 

RedisError: TVS.CREATEINDEX command doesn't exist in Redis commands

**Comment by yangbodong22011** [comment]
Can you provide the complete error stack?
Please note: avoid leaking sensitive information such as instance ID and password.

**Comment by rifandyzv** [comment]
Already solved, redeployed the instance and now working perfectly
